#!/usr/bin/env python3
"""Guard the pandoc version used to build the site.

The committed HTML under ``docs/`` is generated by pandoc, and pandoc's
boilerplate output (table-row classes, footnote wrappers, section vs aside)
varies between versions. Building with a different pandoc than the one that
produced the committed baseline yields large cosmetic-only diffs. This guard
keeps the generated site reproducible by checking the local pandoc against
the version pinned in ``.pandoc-version``.

Usage:
    python3 pandoc_version.py        # strict: exit non-zero on mismatch
    from pandoc_version import check
    check()                          # soft: warn and return False on mismatch
"""
import subprocess
import sys
from pathlib import Path

PIN_FILE = Path(__file__).with_name('.pandoc-version')


def pinned_version():
    return PIN_FILE.read_text(encoding='utf-8').strip()


def local_version():
    out = subprocess.run(
        ['pandoc', '--version'],
        capture_output=True, text=True, check=True,
    ).stdout
    # First line is e.g. "pandoc 3.6.4"
    return out.splitlines()[0].split()[1]


def check(strict=False):
    """Compare local pandoc to the pin. Warn (or exit, if strict) on mismatch.

    Returns True when the local pandoc matches the pin, False otherwise.
    """
    pinned = pinned_version()
    try:
        local = local_version()
    except FileNotFoundError:
        msg = 'pandoc not found on PATH'
        if strict:
            sys.exit(f'   ✗ {msg}')
        print(f'   ⚠ {msg}')
        return False
    except (subprocess.CalledProcessError, IndexError):
        msg = 'could not determine local pandoc version'
        if strict:
            sys.exit(f'   ✗ {msg}')
        print(f'   ⚠ {msg}')
        return False

    if local != pinned:
        msg = (f'pandoc {local} does not match pinned {pinned} '
               f'(.pandoc-version); generated HTML will differ cosmetically. '
               f'Install pandoc {pinned}, or update .pandoc-version and '
               f'regenerate the whole site in one commit.')
        if strict:
            sys.exit(f'   ✗ {msg}')
        print(f'   ⚠ {msg}')
        return False
    return True


if __name__ == '__main__':
    check(strict=True)
    print(f'   ✓ pandoc {pinned_version()} matches .pandoc-version')
